export const jobs = [
  {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },
  {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  }, {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },
  {
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },{
    companyName: "Fidelity Investments",
    companyEmail: "carree@fidelity.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/fidelity.jpeg",
    jobTitle: "Senior AI/ML Engineer",
    jobLink: "https://jobs.fidelity.com/job-details/18989426/senior-ai-ml-engineer-durham-nc/",
    type: "fulltime",
    id: "job001",
  },
  {
    companyName: "Wipro",
    companyEmail: "hr@wipro.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/wipro.png",
    jobTitle: "Data Engineer - Apache Spark",
    jobLink: "https://careers.wipro.com/careers-home/jobs/3023685/job",
    type: "fulltime",
    id: "job002",
  },
  {
    companyName: "Apple",
    companyEmail: "jobs@apple.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/apple.jpeg",
    jobTitle: "Senior Safety Test Engineer, Autonomous Systems",
    jobLink: "https://jobs.apple.com/en-us/details/200422203/senior-safety-test-engineer-autonomous-systems",
    type: "fulltime",
    id: "job003",
  },
  {
    companyName: "Nike",
    companyEmail: "hr@nike.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nike.png",
    jobTitle: "Senior Software Engineer - ServiceNow",
    jobLink: "https://jobs.nike.com/?jobSearch=true&jsOffset=0&jsSort=posting_start_date&jsLanguage=en&error=jobPost",
    type: "fulltime",
    id: "job004",
  },
  {
    companyName: "Leidos",
    companyEmail: "careers@leidos.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/leidos.jpeg",
    jobTitle: "SATCOM Training Specialist",
    jobLink: "https://careers.leidos.com/jobs/13284983-satcom-training-specialist",
    type: "fulltime",
    id: "job005",
  },
  {
    companyName: "J.P. Morgan",
    companyEmail: "carree@jpmorgan.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/jpmorganchase.png",
    jobTitle: "Software Engineer III - Pega Application Developer",
    jobLink: "https://jpmc.fa.oraclecloud.com/hcmUI/CandidateExperience/en/sites/CX_1001/job/210443420",
    type: "fulltime",
    id: "job006",
  },
  {
    companyName: "Nvidia",
    companyEmail: "carree@nvidia.com",
    companyLogo: "https://s3.amazonaws.com/refer.me/company_logos/nvidia.png",
    jobTitle: "Senior Business Development Manager, Generative AI",
    jobLink: "https://nvidia.wd5.myworkdayjobs.com/en-US/NVIDIAExternalCareerSite/job/US-DC-Remote/Senior-Business-Development-Manager--Generative-AI_JR1971620",
    type: "fulltime",
    id: "job007",
  },
  {
    companyName: "TikTok",
    companyEmail: "careers@tiktok.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/tiktok.jpg",
    jobTitle: "Senior Product Manager, Ads Delivery",
    jobLink: "https://careers.tiktok.com/position/7270571140221389115/detail",
    type: "fulltime",
    id: "job008",
  },
  {
    companyName: "Google",
    companyEmail: "carree@google.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/google.jpeg",
    jobTitle: "Field Sales Manager, Google Cloud",
    jobLink: "https://www.google.com/about/careers/applications/jobs/results/98254773263704774-field-sales-manager/",
    type: "internship",
    id: "job009",
  },
  {
    companyName: "Amazon",
    companyEmail: "carree@amazon.com",
    companyLogo: "https://s3.us-east-1.amazonaws.com/refer.me/company_logos/amazon.jpeg",
    jobTitle: "Front End Engineer II , AWS Marketing - Marketing Tech",
    jobLink: "https://www.amazon.jobs/en/jobs/2435387/front-end-engineer-ii-aws-marketing-marketing-tech?cmpid=JB_INOP301245B",
    type: "internship",
    id: "job010",
  },
];
